import type { WorkflowProcessDefinition } from "@/lib/workflow/types";

/**
 * Konkreter P01-Workflow aus vorhandenen Scripts, Pipeline-Keys und Pfaden.
 * SAP-Reportnamen sind nicht im Repo belegt → Platzhalter / Projektkonfiguration.
 */
export const EXTRACT_ENTERPRISE_KNOWLEDGE_PROCESS_ID =
  "extract_enterprise_knowledge";

export const extractEnterpriseKnowledgeProcess: WorkflowProcessDefinition = {
  id: EXTRACT_ENTERPRISE_KNOWLEDGE_PROCESS_ID,
  title: "Unternehmenswissen extrahieren",
  description:
    "Operativer Fahrplan: SAP-Exporte ablegen, prüfen, kanonisieren, analysieren, indexieren und freigeben.",
  steps: [
    {
      id: "prep.project_config",
      phase: "Projekt vorbereiten",
      phase_order: 1,
      sequence: 1,
      title: "Projektkonfiguration prüfen",
      short_description:
        "Customer-ID, System-ID, LOCAL_DATA_ROOT und Export-Reports in der Admin-App pflegen.",
      step_type: "manual_instruction",
      execution_location: "Admin-App",
      system_name: "Universal Knowledge Analyzer – Admin",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "customer_id", value: "${CUSTOMER_ID}" },
        { key: "system_id", value: "${SYSTEM_ID}" },
        { key: "LOCAL_DATA_ROOT", value: "${LOCAL_DATA_ROOT}" },
        { key: "PROJECT_DATA_ROOT", value: "${PROJECT_DATA_ROOT}" },
        {
          key: "repository_export_report",
          value: "${REPOSITORY_EXPORT_REPORT}",
        },
        {
          key: "table_definition_export_report",
          value: "${TABLE_DEFINITION_EXPORT_REPORT}",
        },
        {
          key: "table_content_export_report",
          value: "${TABLE_CONTENT_EXPORT_REPORT}",
        },
      ],
      expected_input: "Zugang zum Admin-Bereich",
      expected_output: "Gespeicherte Projektkonfiguration unter app-config/projects.json",
      destination_path: "${LOCAL_DATA_ROOT}/app-config/projects.json",
      file_patterns: ["projects.json"],
      app_action: "Projekt öffnen und Speichern",
      success_criteria: [
        "customer_id und system_id gesetzt",
        "LOCAL_DATA_ROOT erreichbar",
        "Export-Reportfelder gepflegt oder bewusst als „noch zu konfigurieren“ belassen",
      ],
      warning_text:
        "Ohne korrekte Customer-/System-ID zeigen spätere Pfade und Pipeline-Aufrufe auf die falschen Ordner.",
      troubleshooting: [
        "Seite /admin/project öffnen und Werte speichern",
        "LOCAL_DATA_ROOT in .env.local prüfen",
      ],
      actions: ["copy_value", "copy_path", "open_guide", "mark_done"],
      depends_on: [],
      output_checks: [],
    },
    {
      id: "prep.init_layout",
      phase: "Projekt vorbereiten",
      phase_order: 1,
      sequence: 2,
      title: "Projektordner-Layout anlegen",
      short_description:
        "Roh-/Canonical-/Index-Ordner unter dem Projekt anlegen (falls fehlend).",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "Lokales Terminal im Repo general-agent",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "customer", value: "${CUSTOMER_ID}" },
        { key: "system", value: "${SYSTEM_ID}" },
      ],
      expected_input: "Leeres oder bestehendes Projektverzeichnis",
      expected_output:
        "Verzeichnisse raw/classes, raw/control-tables/…, canonical/…, indexes/…, logs/…",
      destination_path: "${PROJECT_DATA_ROOT}",
      file_patterns: [],
      app_action: "Verarbeitung starten (init-layout) oder CLI ausführen",
      success_criteria: [
        "Ordner raw/classes existiert",
        "Ordner raw/control-tables/definitions existiert",
        "Ordner raw/control-tables/contents existiert",
      ],
      warning_text: "Bestehende Dateien werden nicht überschrieben; nur Ordner werden angelegt.",
      troubleshooting: [
        "CLI: npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --init-layout",
      ],
      pipeline_key: null,
      npm_script: "pipeline",
      cli_command:
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --init-layout",
      actions: [
        "copy_value",
        "open_folder",
        "start_pipeline",
        "validate_files",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["prep.project_config"],
      output_checks: [
        "raw/classes",
        "raw/control-tables/definitions",
        "raw/control-tables/contents",
      ],
    },
    {
      id: "sap.repository_export",
      phase: "SAP Repository exportieren",
      phase_order: 2,
      sequence: 3,
      title: "ABAP Repository exportieren",
      short_description:
        "Klassen-/Repository-Export im SAP GUI ausführen und JSONL erzeugen.",
      step_type: "manual_instruction",
      execution_location: "SAP GUI",
      system_name: "${SAP_SYSTEM_LABEL}",
      transaction_or_report: "${REPOSITORY_EXPORT_REPORT}",
      variant: "${REPOSITORY_EXPORT_VARIANT}",
      parameters: [
        { key: "Kunde/Projekt", value: "${CUSTOMER_ID}" },
        { key: "Objektpräfixe", value: "${OBJECT_PREFIXES}" },
        { key: "Klassen", value: "aktiv (falls im Report vorhanden)" },
        {
          key: "Programme / Funktionsbausteine / Erweiterungen",
          value: "noch zu konfigurieren – Reportparameter nicht im Repo belegt",
        },
      ],
      expected_input: "SAP-Berechtigung für den Export-Report",
      expected_output:
        "Mindestens eine JSONL-Datei mit Klassenexport (Ist-Stand P01: eine Datei unter raw/classes)",
      destination_path: "${REPOSITORY_RAW_PATH}",
      file_patterns: ["*.jsonl"],
      app_action: "Danach Dateien lokal ablegen und prüfen",
      success_criteria: [
        "Export im SAP GUI ohne Abbruch durchgelaufen",
        "JSONL-Datei(en) erzeugt",
      ],
      warning_text:
        "Reportname und Variante sind im Git-Repository nicht hinterlegt – unter /admin/project eintragen.",
      troubleshooting: [
        "Reportnamen mit dem SAP-Entwicklungsteam klären",
        "Wert in Projektkonfiguration speichern, dann diese Seite neu laden",
      ],
      actions: [
        "copy_report",
        "copy_parameters",
        "copy_path",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["prep.init_layout"],
    },
    {
      id: "sap.table_definitions_export",
      phase: "Z-/Y-Tabellen exportieren",
      phase_order: 3,
      sequence: 4,
      title: "Z-/Y-Tabellendefinitionen exportieren",
      short_description:
        "Steuertabellen-Definitionen (Metadaten) aus SAP exportieren.",
      step_type: "manual_instruction",
      execution_location: "SAP GUI",
      system_name: "${SAP_SYSTEM_LABEL}",
      transaction_or_report: "${TABLE_DEFINITION_EXPORT_REPORT}",
      variant: "${TABLE_EXPORT_VARIANT}",
      parameters: [
        { key: "Kunde/Projekt", value: "${CUSTOMER_ID}" },
        { key: "Objektpräfixe", value: "${OBJECT_PREFIXES}" },
      ],
      expected_input: "SAP-Berechtigung für Tabellenexport",
      expected_output:
        "JSONL mit Tabellendefinitionen (Ist P01: sap_z_control_tables._all.jsonl)",
      destination_path: "${TABLE_DEFINITIONS_RAW_PATH}",
      file_patterns: ["*.jsonl"],
      app_action: "Datei unter definitions ablegen, danach prüfen",
      success_criteria: [
        "Export ohne Abbruch",
        "Mindestens eine nicht-leere JSONL-Datei",
      ],
      warning_text:
        "Konkreter Reportname fehlt im Repo – bitte in der Projektkonfiguration hinterlegen.",
      troubleshooting: [
        "Mit SAP-Team Report für Definitions-Export klären",
      ],
      actions: [
        "copy_report",
        "copy_parameters",
        "copy_path",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["prep.init_layout"],
    },
    {
      id: "sap.table_contents_export",
      phase: "Z-/Y-Tabellen exportieren",
      phase_order: 3,
      sequence: 5,
      title: "Z-/Y-Tabelleninhalte exportieren",
      short_description: "Steuertabellen-Inhalte (Zeilen) aus SAP exportieren.",
      step_type: "manual_instruction",
      execution_location: "SAP GUI",
      system_name: "${SAP_SYSTEM_LABEL}",
      transaction_or_report: "${TABLE_CONTENT_EXPORT_REPORT}",
      variant: "${TABLE_EXPORT_VARIANT}",
      parameters: [
        { key: "Kunde/Projekt", value: "${CUSTOMER_ID}" },
        { key: "Objektpräfixe", value: "${OBJECT_PREFIXES}" },
      ],
      expected_input: "SAP-Berechtigung für Inhalts-Export",
      expected_output:
        "JSONL mit Tabelleninhalten (Ist P01: sap_z_control_tables_all_cont.jsonl)",
      destination_path: "${TABLE_CONTENTS_RAW_PATH}",
      file_patterns: ["*.jsonl"],
      app_action: "Datei unter contents ablegen, danach prüfen",
      success_criteria: [
        "Export ohne Abbruch",
        "Mindestens eine nicht-leere JSONL-Datei",
      ],
      warning_text:
        "Konkreter Reportname fehlt im Repo – bitte in der Projektkonfiguration hinterlegen.",
      troubleshooting: [
        "Mit SAP-Team Report für Contents-Export klären",
      ],
      actions: [
        "copy_report",
        "copy_parameters",
        "copy_path",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["prep.init_layout"],
    },
    {
      id: "files.place_repository",
      phase: "Dateien lokal ablegen",
      phase_order: 4,
      sequence: 6,
      title: "Repository-Export lokal ablegen",
      short_description:
        "Exportierte Klassen-JSONL in den Rohdatenordner kopieren.",
      step_type: "file_delivery",
      execution_location: "lokaler Rechner",
      system_name: "Dateisystem unter LOCAL_DATA_ROOT",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "Zielordner", value: "${REPOSITORY_RAW_PATH}" },
        { key: "Muster", value: "*.jsonl" },
      ],
      expected_input: "Export-Datei(en) vom SAP-Lauf",
      expected_output: "JSONL unter raw/classes (z. B. ${CUSTOMER_ID}_*.jsonl)",
      destination_path: "${REPOSITORY_RAW_PATH}",
      file_patterns: ["*.jsonl"],
      app_action: "Ordner öffnen / Dateien auswählen, danach prüfen",
      success_criteria: [
        "Mindestens eine .jsonl-Datei im Zielordner",
        "Datei nicht leer",
      ],
      warning_text:
        "Rohdatenordner ist read-only für die Pipeline – Dateien hierher legen, nicht nach canonical/.",
      troubleshooting: [
        "Pfad kopieren und im Finder/Explorer öffnen",
        "Upload über „Dateien auswählen“ nutzen",
      ],
      actions: [
        "copy_path",
        "open_folder",
        "select_files",
        "validate_files",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["sap.repository_export"],
      output_checks: ["raw/classes"],
    },
    {
      id: "files.place_tables",
      phase: "Dateien lokal ablegen",
      phase_order: 4,
      sequence: 7,
      title: "Tabellen-Exporte lokal ablegen",
      short_description:
        "Definitions- und Contents-JSONL in die Rohdatenordner legen.",
      step_type: "file_delivery",
      execution_location: "lokaler Rechner",
      system_name: "Dateisystem unter LOCAL_DATA_ROOT",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "Definitionen", value: "${TABLE_DEFINITIONS_RAW_PATH}" },
        { key: "Inhalte", value: "${TABLE_CONTENTS_RAW_PATH}" },
      ],
      expected_input: "Beide SAP-Tabellenexporte",
      expected_output: "Je mindestens eine JSONL in definitions und contents",
      destination_path: "${PROJECT_DATA_ROOT}/raw/control-tables",
      file_patterns: ["definitions/*.jsonl", "contents/*.jsonl"],
      app_action: "Dateien ablegen und prüfen",
      success_criteria: [
        "definitions: ≥1 nicht-leere .jsonl",
        "contents: ≥1 nicht-leere .jsonl",
      ],
      warning_text: "Beide Unterordner werden für canonicalize:control-tables benötigt.",
      troubleshooting: [
        "Dateinamen dürfen vom P01-Beispiel abweichen, Endung muss .jsonl sein",
      ],
      actions: [
        "copy_path",
        "open_folder",
        "select_files",
        "validate_files",
        "open_guide",
        "mark_done",
      ],
      depends_on: [
        "sap.table_definitions_export",
        "sap.table_contents_export",
      ],
      output_checks: [
        "raw/control-tables/definitions",
        "raw/control-tables/contents",
      ],
    },
    {
      id: "validate.repository_files",
      phase: "Dateien in der App prüfen",
      phase_order: 5,
      sequence: 8,
      title: "Repository-Dateien prüfen",
      short_description:
        "Prüft raw/classes auf vorhandene, nicht-leere, lesbare JSONL.",
      step_type: "validation",
      execution_location: "Admin-App",
      system_name: "Universal Knowledge Analyzer – Admin",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "Pfad", value: "${REPOSITORY_RAW_PATH}" },
        { key: "Muster", value: "*.jsonl" },
      ],
      expected_input: "Abgelegte Repository-JSONL",
      expected_output: "Prüfprotokoll ohne Fehler",
      destination_path: "${REPOSITORY_RAW_PATH}",
      file_patterns: ["*.jsonl"],
      app_action: "Dateien prüfen",
      success_criteria: [
        "≥1 .jsonl vorhanden",
        "keine Datei leer",
        "JSONL zeilenweise parsebar",
      ],
      warning_text: "Keine erfundenen Erfolge – nur Dateisystemprüfung.",
      troubleshooting: [
        "Leere Dateien erneut aus SAP exportieren",
        "Encoding/Zeilenumbrüche prüfen",
      ],
      actions: [
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["files.place_repository"],
      output_checks: ["raw/classes"],
    },
    {
      id: "validate.table_files",
      phase: "Dateien in der App prüfen",
      phase_order: 5,
      sequence: 9,
      title: "Tabellen-Dateien prüfen",
      short_description:
        "Prüft definitions- und contents-JSONL auf Lesbarkeit.",
      step_type: "validation",
      execution_location: "Admin-App",
      system_name: "Universal Knowledge Analyzer – Admin",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "Definitionen", value: "${TABLE_DEFINITIONS_RAW_PATH}" },
        { key: "Inhalte", value: "${TABLE_CONTENTS_RAW_PATH}" },
      ],
      expected_input: "Abgelegte Tabellen-JSONL",
      expected_output: "Prüfprotokoll ohne Fehler",
      destination_path: "${PROJECT_DATA_ROOT}/raw/control-tables",
      file_patterns: ["definitions/*.jsonl", "contents/*.jsonl"],
      app_action: "Dateien prüfen",
      success_criteria: [
        "definitions und contents je ≥1 .jsonl",
        "keine Datei leer",
        "JSONL zeilenweise parsebar",
      ],
      warning_text: "Beide Ordner müssen gültig sein, sonst schlägt die Kanonisierung fehl.",
      troubleshooting: [
        "Fehlende Seite erneut exportieren",
        "Falschen Ordner (definitions vs. contents) korrigieren",
      ],
      actions: [
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["files.place_tables"],
      output_checks: [
        "raw/control-tables/definitions",
        "raw/control-tables/contents",
      ],
    },
    {
      id: "pipeline.canonicalize_classes",
      phase: "Kanonisierung ausführen",
      phase_order: 6,
      sequence: 10,
      title: "SAP-Klassen kanonisieren",
      short_description: "raw/classes → canonical/classes (ohne OpenAI).",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "Pipeline / npm",
      transaction_or_report: "canonicalize.sap_classes",
      variant: "",
      parameters: [
        { key: "pipeline_key", value: "canonicalize.sap_classes" },
        { key: "npm_script", value: "canonicalize:sap-classes" },
        { key: "customer", value: "${CUSTOMER_ID}" },
      ],
      expected_input: "raw/classes/*.jsonl",
      expected_output:
        "canonical/classes/code_units.jsonl, source_objects.jsonl, relations.jsonl, …",
      destination_path: "${PROJECT_DATA_ROOT}/canonical/classes",
      file_patterns: ["code_units.jsonl"],
      app_action: "Verarbeitung starten",
      success_criteria: [
        "canonical/classes/code_units.jsonl existiert und ist nicht leer",
        "CLI-Exitcode 0",
      ],
      warning_text: "Script ist derzeit auf Projektordner P01 hardcodiert in scripts/canonicalize-sap-classes.ts.",
      troubleshooting: [
        "npm run canonicalize:sap-classes",
        "oder: npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step canonicalize.sap_classes",
      ],
      pipeline_key: "canonicalize.sap_classes",
      npm_script: "canonicalize:sap-classes",
      cli_command:
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step canonicalize.sap_classes",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["validate.repository_files"],
      output_checks: ["canonical/classes/code_units.jsonl"],
    },
    {
      id: "pipeline.canonicalize_tables",
      phase: "Kanonisierung ausführen",
      phase_order: 6,
      sequence: 11,
      title: "Steuertabellen kanonisieren",
      short_description:
        "raw/control-tables → canonical/control-tables (ohne OpenAI).",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "Pipeline / npm",
      transaction_or_report: "canonicalize.control_tables",
      variant: "",
      parameters: [
        { key: "pipeline_key", value: "canonicalize.control_tables" },
        { key: "npm_script", value: "canonicalize:control-tables" },
      ],
      expected_input: "raw/control-tables/{definitions,contents}/*.jsonl",
      expected_output:
        "canonical/control-tables/table_definitions.jsonl, table_rows.jsonl, …",
      destination_path: "${PROJECT_DATA_ROOT}/canonical/control-tables",
      file_patterns: ["table_rows.jsonl", "table_definitions.jsonl"],
      app_action: "Verarbeitung starten",
      success_criteria: [
        "table_definitions.jsonl und table_rows.jsonl vorhanden und nicht leer",
        "CLI-Exitcode 0",
      ],
      warning_text: "Script derzeit auf P01 hardcodiert in scripts/canonicalize-control-tables.ts.",
      troubleshooting: [
        "npm run canonicalize:control-tables",
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step canonicalize.control_tables",
      ],
      pipeline_key: "canonicalize.control_tables",
      npm_script: "canonicalize:control-tables",
      cli_command:
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step canonicalize.control_tables",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["validate.table_files"],
      output_checks: [
        "canonical/control-tables/table_definitions.jsonl",
        "canonical/control-tables/table_rows.jsonl",
      ],
    },
    {
      id: "pipeline.analyze_code",
      phase: "Code analysieren",
      phase_order: 7,
      sequence: 12,
      title: "Code-Units analysieren (OpenAI)",
      short_description:
        "canonical code_units → unit_analyses. Expliziter Schritt, benötigt OpenAI.",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "Pipeline / npm + OpenAI",
      transaction_or_report: "analyze.sap_code_units",
      variant: "",
      parameters: [
        { key: "pipeline_key", value: "analyze.sap_code_units" },
        { key: "npm_script", value: "analyze:sap-code-units" },
        { key: "requires_openai", value: "true" },
        { key: "explicit_only", value: "true" },
      ],
      expected_input: "canonical/classes/code_units.jsonl",
      expected_output: "analyses/classes/unit_analyses.jsonl",
      destination_path: "${PROJECT_DATA_ROOT}/analyses/classes",
      file_patterns: ["unit_analyses.jsonl"],
      app_action: "Verarbeitung starten (explizit)",
      success_criteria: [
        "unit_analyses.jsonl vorhanden und nicht leer",
        "CLI-Exitcode 0",
      ],
      warning_text:
        "Verbraucht OpenAI-Tokens. Wird nie automatisch verkettet – nur mit --step.",
      troubleshooting: [
        "OPENAI_API_KEY in .env.local prüfen",
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step analyze.sap_code_units",
      ],
      pipeline_key: "analyze.sap_code_units",
      npm_script: "analyze:sap-code-units",
      cli_command:
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step analyze.sap_code_units",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["pipeline.canonicalize_classes"],
      output_checks: ["analyses/classes/unit_analyses.jsonl"],
    },
    {
      id: "pipeline.index_tables",
      phase: "Tabellen aufbereiten",
      phase_order: 8,
      sequence: 13,
      title: "Tabellen-Wissensindex aufbereiten",
      short_description:
        "Kanonische Tabellen → Knowledge Units, Rule Groups, SearchDocuments unter indexes/tables (ohne Embeddings).",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "npm Script index:tables",
      transaction_or_report: "index:tables",
      variant: "",
      parameters: [
        { key: "npm_script", value: "index:tables" },
        { key: "customer", value: "${CUSTOMER_ID}" },
        { key: "system", value: "${SYSTEM_ID}" },
      ],
      expected_input: "canonical/control-tables/*",
      expected_output:
        "indexes/tables/search_documents.jsonl, table_knowledge_units.jsonl, …",
      destination_path: "${PROJECT_DATA_ROOT}/indexes/tables",
      file_patterns: ["search_documents.jsonl", "index_manifest.json"],
      app_action: "Verarbeitung starten",
      success_criteria: [
        "indexes/tables/search_documents.jsonl nicht leer",
        "index_manifest.json vorhanden",
      ],
      warning_text:
        "Kein Eintrag in der Pipeline-Registry – eigener npm-Befehl. analyze.control_tables bleibt reserved.",
      troubleshooting: [
        "npm run index:tables -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID}",
      ],
      pipeline_key: null,
      npm_script: "index:tables",
      cli_command:
        "npm run index:tables -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID}",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["pipeline.canonicalize_tables"],
      output_checks: [
        "indexes/tables/search_documents.jsonl",
        "indexes/tables/index_manifest.json",
      ],
    },
    {
      id: "pipeline.link_code_tables",
      phase: "Code und Tabellen verknüpfen",
      phase_order: 9,
      sequence: 14,
      title: "Code ↔ Steuertabellen verknüpfen",
      short_description:
        "Deterministische Relationen code_units ↔ table_rows (ohne OpenAI).",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "Pipeline / npm",
      transaction_or_report: "link.code_control_tables",
      variant: "",
      parameters: [
        { key: "pipeline_key", value: "link.code_control_tables" },
        { key: "npm_script", value: "link:code-control-tables" },
      ],
      expected_input:
        "canonical/classes/code_units.jsonl + canonical/control-tables",
      expected_output: "canonical/relations/code_table_links.jsonl",
      destination_path: "${PROJECT_DATA_ROOT}/canonical/relations",
      file_patterns: ["code_table_links.jsonl"],
      app_action: "Verarbeitung starten",
      success_criteria: [
        "code_table_links.jsonl vorhanden und nicht leer",
        "CLI-Exitcode 0",
      ],
      warning_text: "interpret.code_table ist reserved und wird hier nicht gestartet.",
      troubleshooting: [
        "npm run link:code-control-tables",
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step link.code_control_tables",
      ],
      pipeline_key: "link.code_control_tables",
      npm_script: "link:code-control-tables",
      cli_command:
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step link.code_control_tables",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: [
        "pipeline.canonicalize_classes",
        "pipeline.canonicalize_tables",
      ],
      output_checks: ["canonical/relations/code_table_links.jsonl"],
    },
    {
      id: "pipeline.index_search_documents",
      phase: "Suchindex erzeugen",
      phase_order: 10,
      sequence: 15,
      title: "SearchDocuments aus Code-Analysen indexieren",
      short_description:
        "analyses → indexes/classes/search_documents (ohne Embeddings).",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "Pipeline / npm",
      transaction_or_report: "index.search_documents",
      variant: "",
      parameters: [
        { key: "pipeline_key", value: "index.search_documents" },
        { key: "npm_script", value: "index:search-documents" },
      ],
      expected_input: "analyses/classes/unit_analyses.jsonl",
      expected_output: "indexes/classes/search_documents.jsonl",
      destination_path: "${PROJECT_DATA_ROOT}/indexes/classes",
      file_patterns: ["search_documents.jsonl"],
      app_action: "Verarbeitung starten",
      success_criteria: [
        "indexes/classes/search_documents.jsonl vorhanden und nicht leer",
      ],
      warning_text: "Zwischenprodukt; der User-Ask-Flow nutzt primär indexes/search.",
      troubleshooting: [
        "npm run index:search-documents",
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step index.search_documents",
      ],
      pipeline_key: "index.search_documents",
      npm_script: "index:search-documents",
      cli_command:
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step index.search_documents",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["pipeline.analyze_code"],
      output_checks: ["indexes/classes/search_documents.jsonl"],
    },
    {
      id: "pipeline.index_search",
      phase: "Suchindex erzeugen",
      phase_order: 10,
      sequence: 16,
      title: "Hybrid-Search-Index erzeugen",
      short_description:
        "Dokumente + Embeddings → indexes/search (OpenAI Embeddings, explizit).",
      step_type: "pipeline_action",
      execution_location: "CLI",
      system_name: "Pipeline / npm + OpenAI",
      transaction_or_report: "index.search",
      variant: "",
      parameters: [
        { key: "pipeline_key", value: "index.search" },
        { key: "npm_script", value: "index:search" },
        { key: "active_index_path", value: "${ACTIVE_INDEX_PATH}" },
        { key: "requires_openai", value: "true" },
        { key: "explicit_only", value: "true" },
      ],
      expected_input:
        "unit_analyses (+ optional table/relation analyses), table_rows",
      expected_output:
        "indexes/search/search_documents.jsonl, embeddings/search/…, index_manifest.json",
      destination_path: "${PROJECT_DATA_ROOT}/${ACTIVE_INDEX_PATH}",
      file_patterns: ["search_documents.jsonl", "index_manifest.json"],
      app_action: "Verarbeitung starten",
      success_criteria: [
        "search_documents.jsonl nicht leer",
        "index_manifest.json vorhanden",
      ],
      warning_text:
        "Reserved Analysen (table_analyses, code_table_interpretations) können fehlen; Script muss damit umgehen. Kein Auto-Erfolg ohne Artefakte.",
      troubleshooting: [
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step index.search",
        "OPENAI_API_KEY prüfen",
      ],
      pipeline_key: "index.search",
      npm_script: "index:search",
      cli_command:
        "npm run pipeline -- --customer ${CUSTOMER_ID} --system ${SYSTEM_ID} --step index.search",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: [
        "pipeline.analyze_code",
        "pipeline.link_code_tables",
        "pipeline.index_tables",
      ],
      output_checks: [
        "indexes/search/search_documents.jsonl",
        "indexes/search/index_manifest.json",
      ],
    },
    {
      id: "qa.verify_knowledge",
      phase: "Qualitätsprüfung durchführen",
      phase_order: 11,
      sequence: 17,
      title: "Wissensindex verifizieren",
      short_description:
        "Prüft, ob der aktive Search-Index für den Ask-Flow nutzbar ist.",
      step_type: "validation",
      execution_location: "CLI",
      system_name: "npm Script verify:knowledge-index",
      transaction_or_report: "verify:knowledge-index",
      variant: "",
      parameters: [
        { key: "npm_script", value: "verify:knowledge-index" },
        { key: "index", value: "${ACTIVE_INDEX_PATH}" },
      ],
      expected_input: "Aktiver Index unter PROJECT_DATA_ROOT",
      expected_output: "Verify-OK ohne Fehler",
      destination_path: "${PROJECT_DATA_ROOT}/${ACTIVE_INDEX_PATH}",
      file_patterns: ["search_documents.jsonl", "index_manifest.json"],
      app_action: "Dateien prüfen / Verarbeitung starten",
      success_criteria: [
        "Index-Dateien vorhanden",
        "verify:knowledge-index Exitcode 0 oder Dateiprüfung OK",
      ],
      warning_text: "Keine manuellen Erfolgsmeldungen ohne Prüfung.",
      troubleshooting: [
        "npm run verify:knowledge-index",
        "Projekt → active_index_path prüfen",
      ],
      pipeline_key: null,
      npm_script: "verify:knowledge-index",
      cli_command: "npm run verify:knowledge-index",
      actions: [
        "copy_value",
        "start_pipeline",
        "validate_files",
        "show_errors",
        "retry",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["pipeline.index_search"],
      output_checks: [
        "indexes/search/search_documents.jsonl",
        "indexes/search/index_manifest.json",
      ],
    },
    {
      id: "qa.review_index",
      phase: "Qualitätsprüfung durchführen",
      phase_order: 11,
      sequence: 18,
      title: "Index-Manifest und Stichprobe reviewen",
      short_description:
        "Manifest und Dokumentanzahl prüfen; bei Bedarf User-Ansicht testen.",
      step_type: "review",
      execution_location: "Admin-App",
      system_name: "Admin + User-Ansicht",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "manifest", value: "${PROJECT_DATA_ROOT}/${ACTIVE_INDEX_PATH}/index_manifest.json" },
      ],
      expected_input: "Erzeugter Hybrid-Index",
      expected_output: "Bestätigtes Review",
      destination_path: "${PROJECT_DATA_ROOT}/${ACTIVE_INDEX_PATH}",
      file_patterns: ["index_manifest.json"],
      app_action: "Ergebnisbericht öffnen / User-Ansicht",
      success_criteria: [
        "document_count > 0 im Manifest",
        "Stichprobenfrage in /app/ask plausibel",
      ],
      warning_text: "Review bestätigt Qualität – ersetzt keine technische Verify.",
      troubleshooting: [
        "User-Ansicht in neuem Tab öffnen und mit User-Konto anmelden",
      ],
      actions: [
        "open_report",
        "open_guide",
        "mark_done",
      ],
      depends_on: ["qa.verify_knowledge"],
      output_checks: ["indexes/search/index_manifest.json"],
    },
    {
      id: "release.user_access",
      phase: "Anwenderzugriff freigeben",
      phase_order: 12,
      sequence: 19,
      title: "Anwenderzugriff freigeben",
      short_description:
        "User-Konten anlegen/aktivieren und Zugriff auf den Ask-Flow bestätigen.",
      step_type: "approval",
      execution_location: "Admin-App",
      system_name: "Admin → Benutzer",
      transaction_or_report: "",
      variant: "",
      parameters: [
        { key: "Benutzerverwaltung", value: "/admin/users" },
        { key: "User-App", value: "/app" },
      ],
      expected_input: "Freigabeberechtigter Admin",
      expected_output: "Mindestens ein aktiver User mit Projektzuordnung",
      destination_path: "${LOCAL_DATA_ROOT}/app-config/users.json",
      file_patterns: ["users.json"],
      app_action: "Freigabe erteilen",
      success_criteria: [
        "Aktiver User mit Rolle user existiert",
        "User kann /app/ask öffnen",
      ],
      warning_text: "Admin-Checkliste erscheint nicht im User-Bereich.",
      troubleshooting: [
        "Unter /admin/users Benutzer anlegen",
        "Passwort dem Anwender sicher übermitteln",
      ],
      actions: ["grant_approval", "open_guide", "mark_done"],
      depends_on: ["qa.review_index"],
    },
  ],
};
